"""
This document processes the logs generated by the example1, and sums the total number of connected and disconnected pairs used to generate the statistics.
"""

total_connected = 0
with open('log_connected_2017.txt') as f:
    for line in f:
        if 'Going to compute' in line:
            total_connected +=int(line.split()[3])
print 'Total connected:', total_connected

total_disconnected = 0
with open('log_disconnected_2017.txt') as f:
    for line in f:
        if 'Going to compute' in line:
            total_disconnected +=int(line.split()[3])
print 'Total disconnected:', total_disconnected
